#!/usr/bin/env python3
"""
Parse LinkedIn CSV exports and generate src/portfolio.js.
Run from the portfolio root: python3 parse_linkedin.py
"""

import csv
import os
import sys
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
LINKEDIN_DIR = SCRIPT_DIR.parent / "linkedin_export"
PORTFOLIO_JS = SCRIPT_DIR / "src" / "portfolio.js"
IMAGES_DIR = SCRIPT_DIR / "src" / "assets" / "images"
MISSING_MD = SCRIPT_DIR.parent / "missing_info.md"

ICON_MAP = {
    # Embedded / Low-level
    "c": ("C", "fas fa-code"),
    "c++": ("C++", "fas fa-code"),
    "embedded c": ("Embedded C", "fas fa-microchip"),
    "embedded systems": ("Embedded Systems", "fas fa-microchip"),
    "rtos": ("RTOS", "fas fa-cogs"),
    "freertos": ("FreeRTOS", "fas fa-cogs"),
    "arm": ("ARM", "fas fa-microchip"),
    "risc-v": ("RISC-V", "fas fa-microchip"),
    "fpga": ("FPGA", "fas fa-network-wired"),
    "verilog": ("Verilog", "fas fa-code"),
    "soc": ("SoC", "fas fa-microchip"),
    "secure element": ("Secure Element", "fas fa-lock"),
    "trustzone": ("TrustZone", "fas fa-shield-alt"),
    "device drivers": ("Device Drivers", "fas fa-cog"),
    "uefi": ("UEFI", "fas fa-cog"),
    "bootloader": ("Bootloader", "fas fa-cog"),
    "jtag": ("JTAG", "fas fa-plug"),
    "gdb": ("GDB", "fas fa-bug"),
    "uart": ("UART", "fas fa-plug"),
    "spi": ("SPI", "fas fa-plug"),
    "i2c": ("I2C", "fas fa-plug"),
    "usb": ("USB", "fas fa-usb"),
    # Systems / DevOps
    "linux": ("Linux", "fab fa-linux"),
    "python": ("Python", "fab fa-python"),
    "bash": ("Bash", "fas fa-terminal"),
    "git": ("Git", "fab fa-git-alt"),
    "github": ("GitHub", "fab fa-github"),
    "docker": ("Docker", "fab fa-docker"),
    "makefile": ("Makefile", "fas fa-cogs"),
    "cmake": ("CMake", "fas fa-cogs"),
    # Languages
    "java": ("Java", "fab fa-java"),
    "javascript": ("JavaScript", "fab fa-js"),
    "typescript": ("TypeScript", "fab fa-js"),
    "go": ("Go", "fas fa-code"),
    "rust": ("Rust", "fas fa-cog"),
    "assembly": ("Assembly", "fas fa-microchip"),
    # Other
    "jira": ("Jira", "fab fa-jira"),
    "confluence": ("Confluence", "fab fa-atlassian"),
}

MISSING_ICON_SKILLS = []


def icon_for_skill(skill_name):
    key = skill_name.lower().strip()
    if key in ICON_MAP:
        return ICON_MAP[key]
    # Partial match
    for k, v in ICON_MAP.items():
        if k in key or key in k:
            return (skill_name, v[1])
    MISSING_ICON_SKILLS.append(skill_name)
    return (skill_name, "fas fa-code")


def read_csv(filename):
    path = LINKEDIN_DIR / filename
    if not path.exists():
        return None
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        return list(reader)


def fmt_date(date_str):
    if not date_str or date_str.strip() == "":
        return "Present"
    return date_str.strip()


def download_image(url, dest_path, label=""):
    if dest_path.exists():
        print(f"  [exists] {dest_path.name}")
        return True
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=15) as resp, open(dest_path, "wb") as f:
            f.write(resp.read())
        print(f"  [downloaded] {dest_path.name} ({label})")
        return True
    except Exception as e:
        print(f"  [failed] {dest_path.name}: {e}")
        return False


def build_missing_md(missing_items):
    lines = ["# Missing Information Tracker\n\n"]
    lines.append("*Auto-generated by parse_linkedin.py — update manually when data is available.*\n\n")
    for item in missing_items:
        lines.append(f"## {item['section']} — {item['field']}\n")
        lines.append(f"**Why needed:** {item['why']}\n")
        lines.append(f"**Used in:** {item['used_in']}\n")
        lines.append(f"**Placeholder used:** {item['placeholder']}\n\n")
    lines.append("---\n\n## Build Notes\n\n")
    lines.append("- BUILT_WITH=npm (Docker blocked by corporate registry proxy)\n")
    lines.append("- Only Profile.csv was present in linkedin_export/ at time of generation\n\n")
    lines.append("---\n\n## GitHub Secrets Required for CI/CD\n\n")
    lines.append("Add these in repo Settings → Secrets → Actions:\n\n")
    lines.append("- `REACT_APP_GITHUB_TOKEN` — GitHub personal access token (no scope needed)\n")
    lines.append("- `PORTFOLIO_GITHUB_USERNAME` — your GitHub username\n")
    lines.append("- `USE_GITHUB_DATA` — set to `\"true\"` once token is added\n")
    lines.append("- `MEDIUM_USERNAME` — if you have a Medium blog, otherwise leave blank\n\n")
    lines.append("---\n\n## Push Instructions\n\n")
    lines.append("```bash\n")
    lines.append("cd /local/mnt/workspace/portfolio/souvikranju.github.io\n")
    lines.append("git remote add origin https://github.com/souvikranju/souvikranju.github.io.git\n")
    lines.append("git push -u origin master\n")
    lines.append("```\n")
    return "".join(lines)


def main():
    missing = []

    # ── 1. Parse Profile.csv ─────────────────────────────────────────────────
    profile_rows = read_csv("Profile.csv")
    if not profile_rows:
        print("ERROR: linkedin_export/Profile.csv not found. Aborting.")
        sys.exit(1)

    p = profile_rows[0]
    print("Parsed Profile.csv headers:", list(p.keys()))

    first_name = p.get("First Name", "").strip()
    last_name = p.get("Last Name", "").strip()
    full_name = f"{first_name} {last_name}".strip() or "Souvik Pal"
    headline = p.get("Headline", "").strip()
    summary = p.get("Summary", "").strip()
    location = p.get("Location", "").strip() or p.get("Geo Location", "").strip()

    subtitle = summary if len(summary) > len(headline) else headline
    subtitle = subtitle.replace('"', '\\"').replace("\n", " ").strip()

    print(f"  Name    : {full_name}")
    print(f"  Headline: {headline}")
    print(f"  Location: {location}")

    # ── 2. Parse optional CSVs ────────────────────────────────────────────────
    positions = read_csv("Positions.csv") or []
    education_rows = read_csv("Education.csv") or []
    skills_rows = read_csv("Skills.csv") or []
    projects_rows = read_csv("Projects.csv") or []
    certs_rows = read_csv("Certifications.csv") or []

    if not positions:
        missing.append({
            "section": "Work Experience",
            "field": "All positions",
            "why": "Positions.csv not present in linkedin_export/",
            "used_in": "src/portfolio.js → workExperiences.experience[]",
            "placeholder": "Qualcomm Lead Engineer entry inferred from headline"
        })
    if not education_rows:
        missing.append({
            "section": "Education",
            "field": "All schools",
            "why": "Education.csv not present in linkedin_export/",
            "used_in": "src/portfolio.js → educationInfo.schools[]",
            "placeholder": "Section hidden (display: false)"
        })
    if not skills_rows:
        missing.append({
            "section": "Skills",
            "field": "Full skill list",
            "why": "Skills.csv not present in linkedin_export/",
            "used_in": "src/portfolio.js → skillsSection.softwareSkills[]",
            "placeholder": "Skills inferred from headline and summary"
        })
    if not projects_rows:
        missing.append({
            "section": "Projects",
            "field": "All projects",
            "why": "Projects.csv not present in linkedin_export/",
            "used_in": "src/portfolio.js → bigProjects.projects[]",
            "placeholder": "Section hidden (display: false)"
        })

    missing.append({
        "section": "Contact",
        "field": "Phone number",
        "why": "Not in LinkedIn export CSV",
        "used_in": "src/portfolio.js → contactInfo.number",
        "placeholder": "Empty string"
    })
    missing.append({
        "section": "Contact",
        "field": "Email address",
        "why": "Not in LinkedIn export CSV",
        "used_in": "src/portfolio.js → contactInfo.email_address",
        "placeholder": "Empty string"
    })
    missing.append({
        "section": "Social",
        "field": "GitHub username / URL",
        "why": "Not in LinkedIn export CSV",
        "used_in": "src/portfolio.js → socialMediaLinks.github",
        "placeholder": "Empty string — openSource.display set false"
    })
    missing.append({
        "section": "Social",
        "field": "Gmail address",
        "why": "Not in LinkedIn export CSV",
        "used_in": "src/portfolio.js → socialMediaLinks.gmail",
        "placeholder": "Empty string"
    })
    missing.append({
        "section": "Greeting",
        "field": "Resume PDF link",
        "why": "No resume upload path provided",
        "used_in": "src/portfolio.js → greeting.resumeLink",
        "placeholder": "Empty string — button hidden"
    })
    missing.append({
        "section": "Company Logos",
        "field": "Qualcomm logo",
        "why": "Not available in template or Eslam-Abdo repo assets",
        "used_in": "src/portfolio.js → workExperiences.experience[].companylogo",
        "placeholder": "embedded_desien.jpg from Eslam-Abdo repo"
    })

    # ── 3. Build inferred skills from headline/summary ────────────────────────
    inferred_skills_raw = [
        "Embedded C", "C++", "RTOS", "ARM", "RISC-V",
        "FPGA", "Linux", "Python", "Git", "Secure Element",
        "Device Drivers", "SoC", "GDB", "CMake"
    ]

    if skills_rows:
        skill_names = [r.get("Name", "").strip() for r in skills_rows if r.get("Name", "").strip()]
    else:
        skill_names = inferred_skills_raw

    software_skills_js = ""
    for name in skill_names:
        display_name, icon = icon_for_skill(name)
        software_skills_js += f"""    {{
      skillName: "{display_name}",
      fontAwesomeClassname: "{icon}"
    }},\n"""

    if MISSING_ICON_SKILLS:
        missing.append({
            "section": "Skills",
            "field": "Icon Mapping",
            "why": "Skills not found in ICON_MAP — generic icon used",
            "used_in": "src/portfolio.js → skillsSection.softwareSkills[]",
            "placeholder": f"fas fa-code for: {', '.join(MISSING_ICON_SKILLS)}"
        })

    # ── 4. Build work experience from Positions.csv or headline inference ─────
    if positions:
        work_exp_entries = []
        for pos in positions:
            company = pos.get("Company Name", "Unknown").strip()
            role = pos.get("Title", "").strip()
            desc = pos.get("Description", "").strip().replace('"', '\\"').replace("\n", " ")
            start = fmt_date(pos.get("Started On", ""))
            end = fmt_date(pos.get("Finished On", ""))
            date_str = f"{start} – {end}"
            logo_var = f'require("./assets/images/companyPlaceholder.png")'
            work_exp_entries.append(f"""    {{
      role: "{role}",
      company: "{company}",
      companylogo: {logo_var},
      date: "{date_str}",
      desc: "{desc}",
      descBullets: []
    }}""")
        work_exp_js = ",\n".join(work_exp_entries)
        work_display = "true"
    else:
        # Infer Qualcomm from headline
        work_exp_js = """    {
      role: "Lead Embedded Firmware Engineer",
      company: "Qualcomm",
      companylogo: require("./assets/images/embedded_desien.jpg"),
      date: "Present",
      desc: "Working on secure element firmware inside Snapdragon SoCs deployed across Mobile, Compute, XR, and IoT products.",
      descBullets: [
        "Secure Elements and TrustZone security architecture on Snapdragon platforms",
        "FPGA-based pre-silicon validation and board bring-up",
        "Device drivers and low-level systems on ARM and RISC-V architectures"
      ]
    }"""
        work_display = "true"

    # ── 5. Build education from Education.csv ────────────────────────────────
    if education_rows:
        edu_entries = []
        for edu in education_rows:
            school = edu.get("School Name", "").strip()
            degree = edu.get("Degree Name", "").strip()
            start = fmt_date(edu.get("Start Date", ""))
            end = fmt_date(edu.get("End Date", ""))
            notes = edu.get("Notes", "").strip().replace('"', '\\"').replace("\n", " ")
            edu_entries.append(f"""    {{
      schoolName: "{school}",
      logo: require("./assets/images/empty.jpg"),
      subHeader: "{degree}",
      duration: "{start} – {end}",
      desc: "{notes}",
      descBullets: []
    }}""")
        edu_js = ",\n".join(edu_entries)
        edu_display = "true"
    else:
        edu_js = ""
        edu_display = "false"

    # ── 6. Build projects from Projects.csv ──────────────────────────────────
    if projects_rows:
        proj_entries = []
        for proj in projects_rows:
            title = proj.get("Title", "").strip()
            desc = proj.get("Description", "").strip().replace('"', '\\"').replace("\n", " ")
            url = proj.get("Url", "").strip()
            proj_entries.append(f"""    {{
      image: require("./assets/images/empty.jpg"),
      projectName: "{title}",
      projectDesc: "{desc}",
      footerLink: [
        {{ name: "View Project", url: "{url}" }}
      ]
    }}""")
        proj_js = ",\n".join(proj_entries)
        proj_display = "true"
    else:
        proj_js = ""
        proj_display = "false"

    # ── 7. Build certifications from Certifications.csv ──────────────────────
    if certs_rows:
        cert_entries = []
        for cert in certs_rows:
            name = cert.get("Name", "").strip()
            authority = cert.get("Authority", "").strip()
            url = cert.get("Url", "").strip()
            cert_entries.append(f"""    {{
      title: "{name}",
      subtitle: "Issued by {authority}",
      image: require("./assets/images/empty.jpg"),
      imageAlt: "{name} Logo",
      footerLink: [
        {{ name: "View Certificate", url: "{url}" }}
      ]
    }}""")
        cert_js = ",\n".join(cert_entries)
        cert_display = "true"
    else:
        cert_js = ""
        cert_display = "false"

    # ── 8. Download images from Eslam-Abdo ───────────────────────────────────
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    eslam_base = "https://raw.githubusercontent.com/Eslam-Abdo/Eslam-Abdo.github.io/master/src/assets/images"
    for fname in ["embedded_desien.jpg", "empty.jpg"]:
        dest = IMAGES_DIR / fname
        download_image(f"{eslam_base}/{fname}", dest, "Eslam-Abdo repo")

    # ── 9. Build skill bullets from summary ──────────────────────────────────
    skill_bullets = [
        "⚡ Designing and optimizing low-level firmware for production-grade embedded platforms",
        "⚡ Secure element firmware development on Snapdragon SoCs across Mobile, XR, and IoT",
        "⚡ FPGA-based pre-silicon validation, board bring-up, and hardware–software debugging on ARM & RISC-V"
    ]
    skill_bullets_js = "\n    ".join([f'emoji("{b}"),' for b in skill_bullets])

    # ── 10. Assemble portfolio.js ─────────────────────────────────────────────
    portfolio_js = f"""/* Change this file to get your personal Portfolio */

// To change portfolio colors globally go to the  _globalColor.scss file

import emoji from "react-easy-emoji";
import splashAnimation from "./assets/lottie/splashAnimation";

// Splash Screen

const splashScreen = {{
  enabled: true,
  animation: splashAnimation,
  duration: 2000
}};

// Summary And Greeting Section

const illustration = {{
  animated: true
}};

const greeting = {{
  username: "{full_name}",
  title: "Hi, I'm {first_name} 👋",
  subTitle: emoji(
    "{subtitle} 🚀"
  ),
  resumeLink: "",
  displayGreeting: true
}};

// Social Media Links

const socialMediaLinks = {{
  github: "",
  linkedin: "https://www.linkedin.com/in/souvikranju/",
  gmail: "",
  gitlab: "",
  facebook: "",
  medium: "",
  stackoverflow: "",
  display: true
}};

// Skills Section

const skillsSection = {{
  title: "What I Do",
  subTitle: "LEAD EMBEDDED FIRMWARE ENGINEER BUILDING SECURE, RELIABLE LOW-LEVEL SYSTEMS",
  skills: [
    {skill_bullets_js}
  ],
  softwareSkills: [
{software_skills_js}  ],
  display: true
}};

// Education Section

const educationInfo = {{
  display: {edu_display},
  schools: [
{edu_js}
  ]
}};

// Tech Stack / Proficiency Bars

const techStack = {{
  viewSkillBars: false,
  experience: [],
  displayCodersrank: false
}};

// Work Experience Section

const workExperiences = {{
  display: {work_display},
  experience: [
{work_exp_js}
  ]
}};

// Open Source Section

const openSource = {{
  showGithubProfile: "false",
  display: false
}};

// Big Projects Section

const bigProjects = {{
  title: "Projects",
  subtitle: "Projects I have built or contributed to",
  projects: [
{proj_js}
  ],
  display: {proj_display}
}};

// Achievement Section

const achievementSection = {{
  title: emoji("Achievements And Certifications 🏆"),
  subtitle: "Certifications and recognitions",
  achievementsCards: [
{cert_js}
  ],
  display: {cert_display}
}};

// Blogs Section

const blogSection = {{
  title: "Blogs",
  subtitle: "",
  displayMediumBlogs: "false",
  blogs: [],
  display: false
}};

// Talks Section

const talkSection = {{
  title: "Talks",
  subtitle: emoji(""),
  talks: [],
  display: false
}};

// Podcast Section

const podcastSection = {{
  title: emoji("Podcast 🎙️"),
  subtitle: "",
  podcast: [],
  display: false
}};

// Resume Section

const resumeSection = {{
  title: "Resume",
  subtitle: "Feel free to download my resume",
  display: false
}};

// Contact Section

const contactInfo = {{
  title: emoji("Contact Me ☎️"),
  subtitle: "Discuss a project or just want to say hi? My inbox is open for all.",
  number: "",
  email_address: ""
}};

// Twitter Section

const twitterDetails = {{
  userName: "",
  display: false
}};

const isHireable = true;

export {{
  illustration,
  greeting,
  socialMediaLinks,
  splashScreen,
  skillsSection,
  educationInfo,
  techStack,
  workExperiences,
  openSource,
  bigProjects,
  achievementSection,
  blogSection,
  talkSection,
  podcastSection,
  contactInfo,
  twitterDetails,
  isHireable,
  resumeSection
}};
"""

    # ── 11. Write output files ────────────────────────────────────────────────
    with open(PORTFOLIO_JS, "w", encoding="utf-8") as f:
        f.write(portfolio_js)
    print(f"\n✓ Wrote {PORTFOLIO_JS}")

    missing_content = build_missing_md(missing)
    with open(MISSING_MD, "w", encoding="utf-8") as f:
        f.write(missing_content)
    print(f"✓ Wrote {MISSING_MD}")

    print("\n── Summary ──────────────────────────────────────────────────────")
    print(f"  Name        : {full_name}")
    print(f"  Skills      : {len(skill_names)} ({', '.join(skill_names[:5])}...)")
    print(f"  Work entries: {len(positions) or 1} (inferred from headline)")
    print(f"  Education   : {len(education_rows)} (from CSV)")
    print(f"  Projects    : {len(projects_rows)}")
    print(f"  Certs       : {len(certs_rows)}")
    print(f"  Missing items logged: {len(missing)}")
    if MISSING_ICON_SKILLS:
        print(f"  Skills needing custom icons: {MISSING_ICON_SKILLS}")
    print("─────────────────────────────────────────────────────────────────")


if __name__ == "__main__":
    main()
