name: Build and Deploy Portfolio

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.PORTFOLIO_GITHUB_USERNAME }}
          USE_GITHUB_DATA: ${{ secrets.USE_GITHUB_DATA }}
          MEDIUM_USERNAME: ${{ secrets.MEDIUM_USERNAME }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
